ConnectorEcosystem#agent-connector-ecosystem
  AgentConnector#local-agent-connector
    SharedCore#shared-core
      SurfaceClient#surface-client
      OriginGate#origin-gate
      ConsentBroker#consent-broker
      GrantCoordinator#grant-coordinator
      LocalAgentRuntime#agent-runtime
      RuntimeBridge#runtime-bridge
      SessionCoordinator#session-coordinator
      CapabilityDispatcher#dispatcher
      ResultPresenter#result-presenter
      RevocationController#revocation
    PlatformBindings#platform-bindings
      IOSConnector#ios-connector
        EmbeddedBrowser#ios-browser
        WebKitBridge#ios-bridge
        NavigationGate#ios-navigation-gate
      MacConnector#mac-connector
        BrowserClient#mac-browser
        LoopbackHTTPListener#mac-listener
        LocalOriginGate#mac-origin-gate
    Scenarios#scenarios
      RequestFlow#ios-request
        FlowStep.step#ios-01
        FlowStep.step#ios-02
        FlowStep.step#ios-03
        FlowStep.step#ios-04
        FlowStep.step#ios-05
      RequestFlow#mac-request
        FlowStep.step#mac-01
        FlowStep.step#mac-02
        FlowStep.step#mac-03
        FlowStep.step#mac-04
        FlowStep.step#mac-05
  ASPApplication#remote-app
    SurfaceManifest#remote-manifest
    ActionExecutor#remote-executor
